name: pudding
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.1.0
  material_symbols_icons: ^4.2719.0
  image_picker: ^1.2.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true

  image_path: "assets/img/logo/pudding_icon.png"

  adaptive_icon_background: "#FFF7D2"
  adaptive_icon_foreground: "assets/img/logo/pudding_icon.png"

  min_sdk_android: 21

flutter:
  uses-material-design: true

  fonts:
    - family: NanumBarunpen
      fonts:
        - asset: assets/fonts/NanumBarunpenB.ttf
          weight: 700
        - asset: assets/fonts/NanumBarunpenR.ttf
          weight: 400

    - family: Lotteria
      fonts:
        - asset: assets/fonts/LotteriaChab.ttf

  assets:
    - assets/img/

